### ISSUE TITLE
Extraneous newline in URL breaks API call

### ISSUE THREAD

**Issue by whitely** [PaloAltoNetworks/pcs-postman#19]
https://github.com/PaloAltoNetworks/pcs-postman/blob/1453b3ce8560b3a1e8be362899935bf2371982fb/Prisma%20Cloud.postman_collection.json#L3056

Steps to reproduce error:
1. Freshly import postman collection
2. Generate login token
3. Call this API in postman
4. Receive 404

Steps to resolve error:
1. Delete this newline `\n` last character in the string
2. That's it!

**Comment by pan0ptic0n** [comment]
Closed by PR #22
